"""Leakage-aware research preparation and controlled baseline modeling."""

from pharmacy_reconciliation.research.baselines import (
    BASELINE_THRESHOLD,
    BaselinePartitions,
    BaselineResult,
    compare_baselines,
    prepare_baseline_partitions,
)
from pharmacy_reconciliation.research.candidate_stability import (
    CANDIDATE_NAMES,
    STABILITY_CV_SPLITS,
    VALIDATION_COMPARISON_THRESHOLDS,
    CandidateStabilityResult,
    CandidateValidationResult,
    analyze_candidate_validation,
    analyze_train_cv_stability,
    fixed_candidate_pipelines,
    matched_recall_comparison,
)
from pharmacy_reconciliation.research.feature_analysis import (
    TUNED_LOGISTIC_C,
    fit_tuned_logistic_coefficients,
    tuned_logistic_pipeline,
)
from pharmacy_reconciliation.research.features import (
    AUDIT_COLUMNS,
    FEATURE_COLUMNS,
    SupplyEndObservationResult,
    SupplyEndTargetConfig,
    build_fill_date_refill_observations,
    build_refill_observations,
    build_supply_end_observation_result,
    build_supply_end_observations,
)
from pharmacy_reconciliation.research.final_evaluation import (
    FINAL_FITTING_POLICY,
    LOCKED_THRESHOLD,
    FinalEvaluationResult,
    evaluate_locked_test,
)
from pharmacy_reconciliation.research.preparation import (
    EXCLUDED_MODEL_COLUMNS,
    MODEL_FEATURE_COLUMNS,
    PREPROCESSING_PLANS,
    TrainMedianPreprocessor,
    chronological_split,
    prepare_temporal_dataset,
)
from pharmacy_reconciliation.research.reduced_features import (
    EXPERIMENTALLY_EXCLUDED_FEATURES,
    REDUCED_FEATURE_COLUMNS,
    ReducedFoldLocalRefillPreprocessor,
    reduced_tuning_searches,
    tune_reduced_models,
)
from pharmacy_reconciliation.research.threshold_analysis import (
    THRESHOLD_GRID,
    ThresholdAnalysisResult,
    analyze_validation_thresholds,
    tuned_full_feature_pipelines,
)
from pharmacy_reconciliation.research.tree_feature_importance import (
    TREE_MODEL_NAMES,
    combined_tree_importance_ranks,
    fit_tuned_tree_importances,
    tuned_tree_pipelines,
)
from pharmacy_reconciliation.research.tuning import (
    TUNING_CV_SPLITS,
    TUNING_SCORING,
    TUNING_TRIALS,
    FoldLocalRefillPreprocessor,
    prepare_tuning_partitions,
    tune_models,
    tuning_searches,
)

__all__ = [
    "AUDIT_COLUMNS",
    "BASELINE_THRESHOLD",
    "BaselinePartitions",
    "BaselineResult",
    "CANDIDATE_NAMES",
    "CandidateStabilityResult",
    "CandidateValidationResult",
    "FEATURE_COLUMNS",
    "FINAL_FITTING_POLICY",
    "FinalEvaluationResult",
    "EXCLUDED_MODEL_COLUMNS",
    "EXPERIMENTALLY_EXCLUDED_FEATURES",
    "MODEL_FEATURE_COLUMNS",
    "LOCKED_THRESHOLD",
    "PREPROCESSING_PLANS",
    "REDUCED_FEATURE_COLUMNS",
    "ReducedFoldLocalRefillPreprocessor",
    "SupplyEndObservationResult",
    "SupplyEndTargetConfig",
    "STABILITY_CV_SPLITS",
    "build_fill_date_refill_observations",
    "build_refill_observations",
    "build_supply_end_observation_result",
    "build_supply_end_observations",
    "TrainMedianPreprocessor",
    "TUNED_LOGISTIC_C",
    "TUNING_CV_SPLITS",
    "TUNING_SCORING",
    "TUNING_TRIALS",
    "TREE_MODEL_NAMES",
    "THRESHOLD_GRID",
    "ThresholdAnalysisResult",
    "VALIDATION_COMPARISON_THRESHOLDS",
    "analyze_candidate_validation",
    "analyze_train_cv_stability",
    "FoldLocalRefillPreprocessor",
    "chronological_split",
    "analyze_validation_thresholds",
    "compare_baselines",
    "combined_tree_importance_ranks",
    "fit_tuned_logistic_coefficients",
    "evaluate_locked_test",
    "fit_tuned_tree_importances",
    "fixed_candidate_pipelines",
    "matched_recall_comparison",
    "prepare_baseline_partitions",
    "prepare_temporal_dataset",
    "prepare_tuning_partitions",
    "reduced_tuning_searches",
    "tune_models",
    "tune_reduced_models",
    "tuning_searches",
    "tuned_logistic_pipeline",
    "tuned_tree_pipelines",
    "tuned_full_feature_pipelines",
]
